name: Build LumeVisuals

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./"LumeVisuals-0.1.6-audit 1-UIFix..."

    steps:
      - name: Checkout latest source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.12'

      - name: Build mod
        run: gradle --no-daemon clean build --stacktrace --console=plain

      - name: Show built files
        run: |
          echo "=== BUILD/LIBS ==="
          ls -lah build/libs/

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: LumeVisuals-MC1.21.4
          path: ./"LumeVisuals-0.1.6-audit 1-UIFix..."/build/libs/*.jar
          if-no-files-found: error
          overwrite: true
          
